### ISSUE TITLE
Strange error when using with 'siege'

### ISSUE THREAD

**Issue by jonathanstowe** [perl6/perl6-http-server-async#28]
When running the ab.pl6 script and hitting it with

    siege -c 32 http://localhost:1666

It periodically comes up with the following

```
No such method 'message' for invocant of type 'Block'
  in sub  at /home/jonathan/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm line 1
  in method reset-time at /home/jonathan/devel/perl6/3rdparty-modules/perl6-http-server-async/lib/HTTP/Server/Async.pm6 (HTTP::Server::Async) line 44
  in block  at /home/jonathan/devel/perl6/3rdparty-modules/perl6-http-server-async/lib/HTTP/Server/Async.pm6 (HTTP::Server::Async) line 68
```

Which is odd as the only reason I can see that it would want a ```message``` is if it were treating something as an Exception but there's nothing in that piece of code that does anything like that.

I'll try and have a look at this a bit later.

**Comment by lizmat** [comment]
Could you check if this is a problem?  Recent fixes in MoarVM may have fixed this.

**Comment by jonathanstowe** [comment]
Yeah that looks like it's better :+1: 
```
Lifting the server siege...
Transactions:		         708 hits
Availability:		      100.00 %
Elapsed time:		      218.50 secs
Data transferred:	        0.00 MB
Response time:		        8.75 secs
Transaction rate:	        3.24 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		       28.34
Successful transactions:         708
Failed transactions:	           0
Longest transaction:	       25.98
Shortest transaction:	        0.15

```

It shows up some other problems (like it slows down,) but we'll do them separately :)

**Comment by tony-o** [comment]
I know what's happening on the slow down, just need to find time to fix it

--
tony.odell@live.com

On March 9, 2017 at 11:51:31 AM, Jonathan Stowe (notifications@github.com<mailto:notifications@github.com>) wrote:

Yeah that looks like it's better 👍

Lifting the server siege...
Transactions:                    708 hits
Availability:                 100.00 %
Elapsed time:                 218.50 secs
Data transferred:               0.00 MB
Response time:                  8.75 secs
Transaction rate:               3.24 trans/sec
Throughput:                     0.00 MB/sec
Concurrency:                   28.34
Successful transactions:         708
Failed transactions:               0
Longest transaction:           25.98
Shortest transaction:           0.15




It shows up some other problems (like it slows down,) but we'll do them separately :)
